# Generated by Django 3.1 on 2020-10-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('subject', models.CharField(max_length=15, verbose_name='Asunto')),
                ('message', models.TextField(max_length=400, verbose_name='Mensaje')),
            ],
        ),
    ]
