# Generated by Django 3.1.3 on 2020-11-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='subject',
            field=models.CharField(max_length=25, verbose_name='Asunto'),
        ),
    ]